# Generated by Django 5.2.8 on 2026-01-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zerver", "0771_alter_realmemoji_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="rendered_description",
            field=models.TextField(null=True, default=None),
        ),
    ]
